name: baltic_wq
channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - pandas=2.1.0
  - numpy=1.23.4
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - esda=2.5.1
  - libpysal=4.12.1
  - scikit-learn=1.3.0
  - shap=0.47.1
  - joblib=1.3.2
  - jupyterlab
  - notebook   
  - ipywidgets